// <auto-generated />
namespace portal_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ajout_User_dateNais_MainAdresse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajout_User_dateNais_MainAdresse));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240916166_Ajout_User_dateNais_MainAdresse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
